on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
  #   branches:
  #     - main
  # pull_request:
  #     types: [opened, synchronize, reopened]
name: Test
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18' # The Go version to download (if necessary) and use.
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
    - name: Run tests
      run: |
        golangci-lint run --out-format checkstyle ./... > golangci-lint-report.out
        go test -coverprofile=coverage.out -json > test-report.out
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=rytsh
          -Dsonar.projectKey=rytsh_call
          -Dsonar.go.coverage.reportPaths=coverage.out
          -Dsonar.go.tests.reportPaths=test-report.out
          -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.out
          -Dsonar.sources=.
          -Dsonar.exclusions=**/vendor/**,**/*_test.go
          -Dsonar.tests=.
          -Dsonar.test.inclusions=**/*_test.go
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
